export type ExampleCategory =
  "Animated" | "Blocks" | "Primitives" | "Storage" | "Behavior"

export interface ExampleMeta {
  name: string
  title: string
  description: string
  category: ExampleCategory
  /** Where the card links: the component's docs page or a guide. */
  href: string
}

export const exampleCategories: ExampleCategory[] = [
  "Animated",
  "Blocks",
  "Primitives",
  "Storage",
  "Behavior",
]

export const examples: ExampleMeta[] = [
  {
    name: "vinyl-upload",
    title: "Vinyl record",
    description: "Music uploads on a spinning record.",
    category: "Animated",
    href: "/docs/components/vinyl-upload",
  },
  {
    name: "rocket-upload",
    title: "Rocket launch",
    description: "Ship build artifacts with a liftoff.",
    category: "Animated",
    href: "/docs/components/rocket-upload",
  },
  {
    name: "battery-upload",
    title: "Battery backup",
    description: "Photo backups that charge a battery.",
    category: "Animated",
    href: "/docs/components/battery-upload",
  },
  {
    name: "typewriter-upload",
    title: "Typewriter",
    description: "Document submissions typed onto a page.",
    category: "Animated",
    href: "/docs/components/typewriter-upload",
  },
  {
    name: "hourglass-upload",
    title: "Hourglass",
    description: "Long uploads with the time left up front.",
    category: "Animated",
    href: "/docs/components/hourglass-upload",
  },
  {
    name: "blueprint-upload",
    title: "Blueprint",
    description: "CAD and drawings traced as they upload.",
    category: "Animated",
    href: "/docs/components/blueprint-upload",
  },
  {
    name: "stamp-upload",
    title: "Rubber stamp",
    description: "Contracts stamped as they're received.",
    category: "Animated",
    href: "/docs/components/stamp-upload",
  },
  {
    name: "delivery-upload",
    title: "Delivery truck",
    description: "Shipping documents on a delivery route.",
    category: "Animated",
    href: "/docs/components/delivery-upload",
  },
  {
    name: "folder-upload",
    title: "Folder upload",
    description: "The folder opens on hover; dropped files fly in.",
    category: "Animated",
    href: "/docs/components/folder-upload",
  },
  {
    name: "upload-island",
    title: "Upload island",
    description: "A pill that morphs between idle, progress and done.",
    category: "Animated",
    href: "/docs/components/upload-island",
  },
  {
    name: "envelope-upload",
    title: "Envelope",
    description: "Files slide into an envelope that seals when sent.",
    category: "Animated",
    href: "/docs/components/envelope-upload",
  },
  {
    name: "paper-plane-button",
    title: "Paper plane button",
    description: "Fills while sending, then the plane takes off.",
    category: "Animated",
    href: "/docs/components/paper-plane-button",
  },
  {
    name: "shopping-bag-upload",
    title: "Shopping bag",
    description: "Product photos drop into a bag that fills up.",
    category: "Animated",
    href: "/docs/components/shopping-bag-upload",
  },
  {
    name: "orbit-upload",
    title: "Orbit",
    description: "Files orbit the center, then land in a row.",
    category: "Animated",
    href: "/docs/components/orbit-upload",
  },
  {
    name: "upload-stack",
    title: "Upload stack",
    description: "Stacked cards that fan out on hover.",
    category: "Animated",
    href: "/docs/components/upload-stack",
  },
  {
    name: "upload-morph-button",
    title: "Morphing button",
    description: "Button → progress → check, in one element.",
    category: "Animated",
    href: "/docs/components/upload-morph-button",
  },
  {
    name: "polaroid-upload",
    title: "Polaroid photos",
    description: "Photos drop in with a spring and a tilt.",
    category: "Animated",
    href: "/docs/components/polaroid-upload",
  },
  {
    name: "image-reveal-upload",
    title: "Image reveal",
    description: "The photo develops behind a scan line as it uploads.",
    category: "Animated",
    href: "/docs/components/image-reveal-upload",
  },
  {
    name: "liquid-dropzone",
    title: "Liquid dropzone",
    description: "Fills up like a glass with the batch progress.",
    category: "Animated",
    href: "/docs/components/liquid-dropzone",
  },
  {
    name: "progress-ring-upload",
    title: "Progress ring",
    description: "One ring, a counting percentage, a drawn check.",
    category: "Animated",
    href: "/docs/components/progress-ring-upload",
  },
  {
    name: "upload-dock",
    title: "Upload dock",
    description: "A dock of files that magnifies under the cursor.",
    category: "Animated",
    href: "/docs/components/upload-dock",
  },
  {
    name: "upload-terminal",
    title: "Upload terminal",
    description: "Uploads printed as a CLI log with ASCII bars.",
    category: "Animated",
    href: "/docs/components/upload-terminal",
  },
  {
    name: "magnetic-dropzone",
    title: "Magnetic dropzone",
    description: "The target leans towards the pointer and dragged files.",
    category: "Animated",
    href: "/docs/components/magnetic-dropzone",
  },
  {
    name: "ripple-dropzone",
    title: "Ripple dropzone",
    description: "Rings ripple while dragging; a burst on drop.",
    category: "Animated",
    href: "/docs/components/ripple-dropzone",
  },
  {
    name: "cloud-dropzone",
    title: "Cloud dropzone",
    description: "Particles rise into a cloud that fills with progress.",
    category: "Animated",
    href: "/docs/components/cloud-dropzone",
  },
  {
    name: "flip-card-upload",
    title: "Flip card",
    description: "The card flips to show the file once it's uploaded.",
    category: "Animated",
    href: "/docs/components/flip-card-upload",
  },
  {
    name: "scanner-upload",
    title: "Document scanner",
    description: "Corner guides and a scan beam for IDs and receipts.",
    category: "Animated",
    href: "/docs/components/scanner-upload",
  },
  {
    name: "upload-odometer",
    title: "Odometer",
    description: "Files, megabytes and percent on rolling digits.",
    category: "Animated",
    href: "/docs/components/upload-odometer",
  },
  {
    name: "upload-confetti",
    title: "Confetti",
    description: "A burst in your theme's colors when a batch finishes.",
    category: "Animated",
    href: "/docs/components/upload-confetti",
  },
  {
    name: "animated-upload-queue",
    title: "Animated queue",
    description: "Rows expand in, collapse out and draw a check.",
    category: "Animated",
    href: "/docs/components/animated-upload-queue",
  },
  {
    name: "product-media-upload",
    title: "Product media",
    description: "Cover image and a reorderable gallery for a storefront.",
    category: "Blocks",
    href: "/docs/components/product-media-upload",
  },
  {
    name: "csv-import",
    title: "CSV import",
    description: "Check columns and preview rows before a bulk import.",
    category: "Blocks",
    href: "/docs/components/csv-import",
  },
  {
    name: "identity-verification",
    title: "Identity verification",
    description: "ID front, back and selfie with a progress rail.",
    category: "Blocks",
    href: "/docs/components/identity-verification",
  },
  {
    name: "document-checklist",
    title: "Document checklist",
    description: "Required documents for a claim, ticked off as they upload.",
    category: "Blocks",
    href: "/docs/components/document-checklist",
  },
  {
    name: "job-application-upload",
    title: "Job application",
    description: "Resume, cover letter and portfolio for a careers page.",
    category: "Blocks",
    href: "/docs/components/job-application-upload",
  },
  {
    name: "ocr-upload",
    title: "OCR upload",
    description: "Read text from scans, photos and PDFs after upload.",
    category: "Blocks",
    href: "/docs/components/ocr-upload",
  },
  {
    name: "receipt-upload",
    title: "Receipt capture",
    description: "Snap a receipt; your OCR fills in the expense.",
    category: "Blocks",
    href: "/docs/components/receipt-upload",
  },
  {
    name: "property-photos",
    title: "Property photos",
    description: "Tag listing photos by room and see what's missing.",
    category: "Blocks",
    href: "/docs/components/property-photos",
  },
  {
    name: "assignment-submission",
    title: "Assignment hand-in",
    description: "Turn in coursework before the deadline.",
    category: "Blocks",
    href: "/docs/components/assignment-submission",
  },
  {
    name: "upload-dialog",
    title: "Upload dialog",
    description: "Pick, review, then upload, in a modal.",
    category: "Blocks",
    href: "/docs/components/upload-dialog",
  },
  {
    name: "upload-popover",
    title: "Attachments popover",
    description: "Attachments behind a button with a progress ring.",
    category: "Blocks",
    href: "/docs/components/upload-popover",
  },
  {
    name: "upload-table",
    title: "Upload table",
    description: "The queue as a data table with a drop overlay.",
    category: "Blocks",
    href: "/docs/components/upload-table",
  },
  {
    name: "upload-tabs",
    title: "Device, link or camera",
    description: "Three sources, one queue.",
    category: "Blocks",
    href: "/docs/components/upload-tabs",
  },
  {
    name: "camera-upload",
    title: "Camera capture",
    description: "Take photos and upload them as you go.",
    category: "Blocks",
    href: "/docs/components/camera-upload",
  },
  {
    name: "logo-upload",
    title: "Logo settings card",
    description: "Preview a logo on light and dark backgrounds.",
    category: "Blocks",
    href: "/docs/components/logo-upload",
  },
  {
    name: "image-metadata",
    title: "Alt text & captions",
    description: "Describe images while they upload.",
    category: "Blocks",
    href: "/docs/components/image-metadata",
  },
  {
    name: "chat-attachment",
    title: "Chat attachments",
    description: "ChatGPT-style composer with paste and drop.",
    category: "Blocks",
    href: "/docs/components/chat-attachments",
  },
  {
    name: "ai-document-upload",
    title: "AI document ingestion",
    description: "Upload, parse, chunk, embed, index.",
    category: "Blocks",
    href: "/docs/components/document-ingest",
  },
  {
    name: "full-window-dropzone",
    title: "Full-window dropzone",
    description: "Drop files anywhere on the page.",
    category: "Blocks",
    href: "/docs/components/global-upload",
  },
  {
    name: "upload-button",
    title: "Upload button",
    description: "A single button with inline progress.",
    category: "Blocks",
    href: "/docs/components/upload-button",
  },
  {
    name: "batch-upload",
    title: "Batch upload",
    description: "Review a selection, then upload it as a batch.",
    category: "Blocks",
    href: "/docs/components/file-upload",
  },
  {
    name: "gallery-upload",
    title: "Gallery",
    description: "Photos resized to WebP, uploaded four at a time.",
    category: "Blocks",
    href: "/docs/components/gallery-upload",
  },
  {
    name: "avatar-upload",
    title: "Avatar upload",
    description: "Round crop and a progress ring.",
    category: "Blocks",
    href: "/docs/components/avatar-upload",
  },
  {
    name: "image-upload",
    title: "Image upload",
    description: "Image grid with in-browser compression.",
    category: "Blocks",
    href: "/docs/components/image-upload",
  },
  {
    name: "video-upload",
    title: "Video",
    description: "Inline playback, duration limits, resumable for large files.",
    category: "Blocks",
    href: "/docs/components/video-upload",
  },
  {
    name: "audio-upload",
    title: "Audio",
    description: "Audio files with an inline player.",
    category: "Blocks",
    href: "/docs/components/audio-upload",
  },
  {
    name: "document-upload",
    title: "Documents & résumé",
    description: "Office documents, plus a single-file résumé field.",
    category: "Blocks",
    href: "/docs/components/document-upload",
  },
  {
    name: "pdf-upload",
    title: "PDF",
    description: "PDF-only uploads with type badges.",
    category: "Blocks",
    href: "/docs/components/document-upload",
  },
  {
    name: "upload-demo",
    title: "Composition",
    description: "Dropzone, list and item parts, composed.",
    category: "Primitives",
    href: "/docs/components/upload",
  },
  {
    name: "upload-card",
    title: "Header, summary, footer",
    description: "UploadHeader, UploadSummary and UploadFooter in a card.",
    category: "Primitives",
    href: "/docs/components/upload#header-footer-and-summary",
  },
  {
    name: "upload-slots",
    title: "Named slots",
    description: "One upload, a slot per required document.",
    category: "Primitives",
    href: "/docs/components/upload#slots",
  },
  {
    name: "upload-overlay",
    title: "Drop overlay",
    description: "Make any content a drop target with UploadOverlay.",
    category: "Primitives",
    href: "/docs/components/upload#overlay",
  },
  {
    name: "upload-dropzone-variants",
    title: "Dropzone variants",
    description: "default, muted and outline.",
    category: "Primitives",
    href: "/docs/components/upload#dropzone",
  },
  {
    name: "upload-dropzone-horizontal",
    title: "Horizontal dropzone",
    description: 'orientation="horizontal" with a trigger.',
    category: "Primitives",
    href: "/docs/components/upload#orientation",
  },
  {
    name: "upload-item-variants",
    title: "Item variants",
    description: "outline, muted and default items.",
    category: "Primitives",
    href: "/docs/components/upload#item",
  },
  {
    name: "upload-item-sizes",
    title: "Item sizes",
    description: "default, sm and xs.",
    category: "Primitives",
    href: "/docs/components/upload#item",
  },
  {
    name: "upload-grid",
    title: "Grid of tiles",
    description: 'variant="grid" lists with tile items.',
    category: "Primitives",
    href: "/docs/components/upload#tiles",
  },
  {
    name: "upload-chips",
    title: "Attachment chips",
    description: "Inline, rounded, extra-small items.",
    category: "Primitives",
    href: "/docs/components/upload#chips",
  },
  {
    name: "upload-trigger",
    title: "Triggers",
    description: "Any element can open the picker.",
    category: "Primitives",
    href: "/docs/components/upload#trigger",
  },
  {
    name: "upload-queue",
    title: "Upload queue",
    description: "Concurrency-limited queue with aggregate progress.",
    category: "Primitives",
    href: "/docs/components/upload",
  },
  {
    name: "custom-upload-ui",
    title: "Custom UI",
    description: "Headless primitives with a completely custom design.",
    category: "Primitives",
    href: "/docs/hooks",
  },
  {
    name: "ui-only-form",
    title: "UI only, no storage",
    description: "Files stay in the browser; the form submits them.",
    category: "Storage",
    href: "/docs/storage/browser",
  },
  {
    name: "custom-adapter",
    title: "Custom adapter",
    description: "Turn any upload function into an adapter.",
    category: "Storage",
    href: "/docs/storage/custom",
  },
  {
    name: "s3-presigned",
    title: "S3 presigned",
    description: "Direct-to-bucket uploads signed by your route.",
    category: "Storage",
    href: "/docs/adapters/s3",
  },
  {
    name: "r2-presigned",
    title: "R2 presigned",
    description: "Cloudflare R2 through its S3-compatible API.",
    category: "Storage",
    href: "/docs/adapters/r2",
  },
  {
    name: "chunked-upload",
    title: "Chunked upload",
    description: "Parallel parts with per-part retry via multipartAdapter.",
    category: "Storage",
    href: "/docs/guides/chunked-uploads",
  },
  {
    name: "resumable-upload",
    title: "Resumable upload",
    description: "Survives reloads with IndexedDB persistence.",
    category: "Storage",
    href: "/docs/guides/resumable-uploads",
  },
  {
    name: "basic-upload",
    title: "Basic upload",
    description: "A dropzone with a queue, in one line.",
    category: "Behavior",
    href: "/docs/components/upload",
  },
  {
    name: "drag-drop",
    title: "Drag and drop",
    description: "Drop files or whole folders; browse as a fallback.",
    category: "Behavior",
    href: "/docs/components/upload#dropzone",
  },
  {
    name: "multiple-upload",
    title: "Multiple files",
    description: "Up to 10 files with per-file progress.",
    category: "Behavior",
    href: "/docs/components/file-upload",
  },
  {
    name: "file-restrictions",
    title: "File restrictions",
    description: "Type, size, count, dimensions, duplicates and custom rules.",
    category: "Behavior",
    href: "/docs/guides/validation",
  },
  {
    name: "required-upload",
    title: "Required upload",
    description: "Native form with hidden inputs and a required rule.",
    category: "Behavior",
    href: "/docs/guides/forms",
  },
  {
    name: "form-upload",
    title: "Form upload",
    description: "react-hook-form + zod; submit waits for uploads.",
    category: "Behavior",
    href: "/docs/components/upload-field",
  },
  {
    name: "image-crop",
    title: "Image crop",
    description: "Crop, zoom, rotate and flip before uploading.",
    category: "Behavior",
    href: "/docs/components/image-cropper",
  },
  {
    name: "image-compression",
    title: "Image compression",
    description: "Resize and re-encode with live savings.",
    category: "Behavior",
    href: "/docs/guides/image-uploads",
  },
  {
    name: "retry",
    title: "Retry",
    description: "Automatic exponential backoff, then manual retry.",
    category: "Behavior",
    href: "/docs/how-it-works",
  },
  {
    name: "pause-resume",
    title: "Pause and resume",
    description: "Resume from the last byte with a resumable adapter.",
    category: "Behavior",
    href: "/docs/guides/resumable-uploads",
  },
  {
    name: "background-upload",
    title: "Background uploads",
    description: "App-level queue that persists across reloads.",
    category: "Behavior",
    href: "/docs/guides/background-uploads",
  },
  {
    name: "error-states",
    title: "Error states",
    description: "Network, 403, 413, blocked and retryable failures.",
    category: "Behavior",
    href: "/docs/how-it-works",
  },
  {
    name: "scan-states",
    title: "Scan states",
    description: "Processing and malware-scan verdicts from the backend.",
    category: "Behavior",
    href: "/docs/guides/processing-and-scanning",
  },
]

export function getExample(name: string) {
  return examples.find((example) => example.name === name)
}
